{% set name = "postal" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a5939a9d419a075f4719a3e193d93b5fd55a936ccc06e0b8956b9982e0faefe

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - nose
    - six
    - libpostal
  run:
    - python
    - libpostal
test:
  imports:
    - postal

about:
  home: https://github.com/openvenues/pypostal
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python bindings to libpostal for fast international address parsing/normalization'
  description: |
    The official Python bindings to libpostal,
    a fast statistical parser/normalizer for street
    addresses anywhere in the world.
  dev_url: https://github.com/openvenues/pypostal

extra:
  recipe-maintainers:
    - MichaelMarien
