schema_version: 1

context:
  name: postal
  version: 1.1.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2158fde6872d57c342b384ca1d0eadd562dc466a8a36f1160919e8189864b1b1

build:
  number: 7
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_{{ target_platform }}
  host:
    - python
    - pip
    - nose
    - six
    - libpostal
    - setuptools
  run:
    - python
    - libpostal
    - six

tests:
  - python:
      imports:
        - postal
        - postal.expand
        - postal.parser
        - postal.near_dupe

about:
  license: MIT
  license_file: LICENSE
  summary: Python bindings to libpostal for fast international address parsing/normalization
  description: |
    The official Python bindings to libpostal,
    a fast statistical parser/normalizer for street
    addresses anywhere in the world.
  homepage: https://github.com/openvenues/pypostal
  repository: https://github.com/openvenues/pypostal

extra:
  recipe-maintainers:
    - MichaelMarien
